'use client';
import { useState, useRef, useEffect } from 'react';
import { MonitorPlay, XCircle, Loader2 } from 'lucide-react';
import styles from './screen-admin.module.css';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type PeerType = any;

export default function AdminScreenClient() {
  const [code, setCode] = useState('');
  const [status, setStatus] = useState<'idle' | 'initializing' | 'registered' | 'calling' | 'connected' | 'error'>('idle');
  const [error, setError] = useState('');
  const [remoteStream, setRemoteStream] = useState<MediaStream | null>(null);
  
  const videoRef = useRef<HTMLVideoElement>(null);
  const peerRef = useRef<PeerType>(null);
  const callRef = useRef<PeerType>(null);

  useEffect(() => {
    return () => disconnect();
  }, []);

  useEffect(() => {
    if (remoteStream && videoRef.current) {
      videoRef.current.srcObject = remoteStream;
      videoRef.current.play().catch(e => {
        console.error('Play error:', e);
        setError('Could not play video: ' + e.message);
      });
    }
  }, [remoteStream, status]);

  const connect = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!code || code.length !== 6) {
      setError('Please enter a valid 6-digit code.');
      return;
    }
    
    setStatus('initializing');
    setError('');

    try {
      const PeerModule = (await import('peerjs')).default;
      const peer = new PeerModule({
        config: {
          iceServers: [
            { urls: 'stun:stun.l.google.com:19302' },
            { urls: 'stun:stun1.l.google.com:19302' },
            { urls: 'stun:stun2.l.google.com:19302' },
          ]
        }
      });
      peerRef.current = peer;

      peer.on('open', (id: string) => {
        console.log('Registered with PeerID:', id);
        setStatus('registered');
        
        // Create a dummy stream to satisfy PeerJS caller requirement
        const canvas = document.createElement('canvas');
        canvas.width = 1; 
        canvas.height = 1;
        const fakeStream = canvas.captureStream(1);
        
        setStatus('calling');
        const call = peer.call(`cif-${code}`, fakeStream);
        callRef.current = call;

        call.on('stream', (stream: MediaStream) => {
          console.log('Received remote stream, active tracks:', stream.getTracks().length);
          setRemoteStream(stream);
          setStatus('connected');
        });

        // Timeout if no stream received in 15 seconds
        setTimeout(() => {
          if (status !== 'connected' && status !== 'error' && status !== 'idle') {
             setError('Connection timed out. Ensure the customer hasn&apos;t closed their window.');
             disconnect();
          }
        }, 15000);

        call.on('close', () => {
          disconnect();
          setError('User stopped sharing their screen.');
        });
        
        call.on('error', (err: any) => {
           console.error('Call error:', err);
           setError(`Call error [${err.type}]: ${err.message}`);
           disconnect();
        });
      });

      peer.on('error', (err: any) => {
        console.error('Peer error:', err);
        setError(`Connection error [${err.type}]: ${err.message}. Ensure the customer is waiting on the share page.`);
        setStatus('error');
      });

    } catch (err: unknown) {
      if (err instanceof Error) setError('Failed to initialize: ' + err.message);
      setStatus('error');
    }
  };

  const getStatusText = () => {
    switch (status) {
      case 'initializing': return 'Starting connection engine...';
      case 'registered': return 'Registered with secure broker...';
      case 'calling': return `Contacting device [${code}]...`;
      case 'connecting' as any: return 'Handshaking...';
      default: return 'Connecting...';
    }
  };

  const disconnect = () => {
    if (callRef.current) {
      callRef.current.close();
      callRef.current = null;
    }
    if (peerRef.current) {
      peerRef.current.destroy();
      peerRef.current = null;
    }
    if (videoRef.current) {
      videoRef.current.srcObject = null;
    }
    setRemoteStream(null);
    setStatus('idle');
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h1>Live Screen Viewer</h1>
        <p>Enter the 6-digit secure code generated by the customer on the <code>/share</code> page.</p>
      </div>

      {status !== 'connected' && (
        <div className={styles.formCard}>
          <MonitorPlay size={48} style={{ color: 'var(--secondary)', marginBottom: '1rem' }} />
          <form onSubmit={connect}>
            <div className={styles.inputGroup}>
              <label htmlFor="code" style={{ display: 'block', marginBottom: '8px', fontWeight: 'bold' }}>Customer PIN</label>
              <input 
                id="code"
                type="text" 
                maxLength={6}
                value={code} 
                onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} 
                placeholder="123456"
                className={styles.pinInput}
                disabled={status !== 'idle' && status !== 'error'}
                autoComplete="off"
              />
            </div>
            
            <button 
              type="submit" 
              className="btn btn-primary" 
              style={{ width: '100%' }}
              disabled={status !== 'idle' && status !== 'error'}
            >
              {status !== 'idle' && status !== 'error' ? (
                <><Loader2 size={20} className="animate-spin" style={{ marginRight: '8px' }} /> {getStatusText()}</>
              ) : 'Connect & View Screen'}
            </button>
          </form>

          {error && (
            <div className={styles.errorMsg}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px', fontWeight: 'bold' }}>
                <XCircle size={20} />
                Connection Failed
              </div>
              {error}
            </div>
          )}
        </div>
      )}

      {status === 'connected' && (
        <div className={styles.videoContainer}>
          <video 
            ref={videoRef} 
            className={styles.videoElement} 
            controls 
            autoPlay 
            playsInline
          />
          <div className={styles.controlsOverlay}>
            <div className={styles.statusIndicator}>
              <div className={styles.recordingDot}></div>
              Live
            </div>
            <button onClick={disconnect} className="btn btn-accent" style={{ padding: '8px 16px', minHeight: 'auto', fontSize: '0.9rem' }}>
              End Session
            </button>
          </div>
        </div>
      )}
    </div>
  );
}